### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by skat00sh** [alexlaurence/NIfTI-Image-Converter#2]
Hi!
While trying to run from the code in latest stable zip file, I am getting this error:
```
Traceback (most recent call last):
  File "nii2png.py", line 159, in <module>
    main(sys.argv[1:])
  File "nii2png.py", line 42, in main
    data_4d = image_array[:, :, i, j]
UnboundLocalError: local variable 'i' referenced before assignment
```
What are these i and j variables for?

**Comment by alexlaurence** [comment]
Hi skat00sh, thank you for the post. 

i is for slice number, j is for volume number. Add 

`i = 0
 j = 0`

above line 41 to fix the issue. Apologies, I'll patch it now :)
